# Generated by Django 5.0.6 on 2025-11-05 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ordertracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_product', 'Viewed Product'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('create_order', 'Created Order'), ('update_order', 'Updated Order'), ('cancel_order', 'Cancelled Order'), ('create_appointment', 'Created Appointment'), ('update_appointment', 'Updated Appointment'), ('cancel_appointment', 'Cancelled Appointment'), ('create_journal', 'Created Journal Entry'), ('update_journal', 'Updated Journal Entry'), ('delete_journal', 'Deleted Journal Entry'), ('submit_feedback', 'Submitted Feedback'), ('view_page', 'Viewed Page')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
