# Generated by Django 5.0.6 on 2025-11-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userhistory_action_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_product', 'Viewed Product'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('create_order', 'Created Order'), ('update_order', 'Updated Order'), ('cancel_order', 'Cancelled Order'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('create_appointment', 'Created Appointment'), ('update_appointment', 'Updated Appointment'), ('cancel_appointment', 'Cancelled Appointment'), ('create_journal', 'Created Journal Entry'), ('update_journal', 'Updated Journal Entry'), ('delete_journal', 'Deleted Journal Entry'), ('submit_feedback', 'Submitted Feedback'), ('view_page', 'Viewed Page')], max_length=20),
        ),
    ]
