# Generated by Django 5.0.6 on 2025-11-15 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userhistory_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_product', 'Viewed Product'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('create_order', 'Created Order'), ('update_order', 'Updated Order'), ('cancel_order', 'Cancelled Order'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('create_reservation', 'Created Reservation'), ('update_reservation', 'Updated Reservation'), ('cancel_reservation', 'Cancelled Reservation'), ('create_journal', 'Created Journal Entry'), ('update_journal', 'Updated Journal Entry'), ('delete_journal', 'Deleted Journal Entry'), ('submit_feedback', 'Submitted Feedback'), ('view_page', 'Viewed Page')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('dine_in', 'Dine In')], default='pickup', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, help_text='Delivery address or pickup location notes')),
                ('notes', models.TextField(blank=True, help_text='Special instructions or requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_instructions', models.TextField(blank=True, help_text='Special cooking instructions for this item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='products',
            field=models.ManyToManyField(through='core.ReservationItem', to='core.product'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
